language: c++
os:
  - linux
  - osx
compiler:
    - clang
sudo: required
env:
    - NINJA_JOBS=2
addons:
   apt:
    sources:
    - george-edison55/cmake-3.x
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - cmake-data
    - ninja-build
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi

script: ./SetupEnv.sh
notifications:
  email: false
